mdickinson/rounders

.flake8, .gitignore, pyproject.toml, setup.cfg
Exclude the top-level `build` directory that's created by the `setuptools` installation in the various tools that might otherwise be confused by it.
=> Exclude build directory

rounder/format.py
We don't need the walruses here, and they prevent the use of this code on Python 3.7. (We might want to drop support for Python 3.7 at some point, but we'd need a more compelling reason than just being able to use walruses.)
=> Remove gratuitous use of walruses

rounder/format.py
mypy doesn't understand the `try` / `except` formulation that we use below, so switch explicitly on Python version instead.
=> Work around mypy error on Python 3.7

.github/workflows/qc.yaml, src/rounder/core.py, src/rounder/decimal_overloads.py, src/rounder/float_overloads.py, src/rounder/format.py, src/rounder/fraction_overloads.py, src/rounder/generics.py, src/rounder/int_overloads.py, src/rounder/mode_specific.py, src/rounder/modes.py, src/rounder/round_to.py, src/rounder/test/test_format.py, src/rounder/test/test_round.py
This PR extends type hints to cover the whole codebase, sufficient to make `mypy --strict` pass.
Ideally we'd avoid the uses of `Any` and provide a tighter definition for the top-level rounding functions, so that the type hints encapsulate the information that the round functions either return an int or something of the same type as the input. However, when I tried to use a type variable for this I ran into https://github.com/python/mypy/issues/13040.
=> Add (and fix) type hints

src/rounder/__init__.py, src/rounder/test/test_format.py
The `format` function is preliminary; don't expose it at top-level.
=> Don't make 'format' publicly available yet

src/rounder/decimal_overloads.py, src/rounder/float_overloads.py, src/rounder/format.py, src/rounder/fraction_overloads.py, src/rounder/generics.py, src/rounder/int_overloads.py, src/rounder/intermediate.py, src/rounder/modes.py, src/rounder/round_to.py
This PR does more internal refactoring and cleanup. The primary change is that intermediate values are now represented with an extra decimal digit rather than a `quarters` field. This is likely a bit less efficient, but it simplifies the conceptual model substantially.
=> Quarters to tenths

README.md, src/rounder/__init__.py, src/rounder/test/test_round.py
This PR adds convenience aliases for `floor`, `ceil` and `trunc`.
```python
>>> from rounder import ceil, floor, trunc
>>> ceil(2.342, 2)
2.35
>>> ceil(-2.342, 2)
-2.34
>>> floor(2.345, 2)
2.34
>>> floor(-2.345, 2)
-2.35
>>> trunc(2.347, 2)
2.34
>>> trunc(-2.347, 2)
-2.34
```
=> Add aliases for floor, ceil and trunc

src/rounders/decimal_overloads.py, src/rounders/format.py
This PR fixes some errors arising with newer versions of our checkers:
- Re-applies black to the codebase, for compatibility with the 2023 black stable style
- Adds a type narrowing assertion to help mypy out
=> Reapply black

src/rounders/decimal_overloads.py, src/rounders/float_overloads.py, src/rounders/format.py, src/rounders/fraction_overloads.py, src/rounders/generics.py, src/rounders/int_overloads.py, src/rounders/intermediate.py, src/rounders/modes.py, src/rounders/round_to.py, src/rounders/test/test_format.py
A minor rework aimed at supporting formatting needs.
Key changes:
- Most of the rounding logic has been moved to the `IntermediateForm` class. The individual rounding modes now only "know" about how to round a value with one digit following the decimal point to an integer.
- `IntermediateForm.sign` is now an `int` rather than a `bool`
- The "preround" step is no longer constrained to round to _exactly_ the right number of digits + 1; it can return any value that rounds correctly (under a minimum constraint on the exponent). For `int` and `Decimal`, `preround` simply converts the value to `IntermediateForm` and does no rounding.
=> Rework rounding machinery

src/rounders/float_overloads.py, src/rounders/format.py, src/rounders/fraction_overloads.py, src/rounders/round_to.py
Since #25, the definition of `preround` didn't match the description, for `float` and `Fraction`: we want the incoming exponent to be the target exponent. The preround machinery is free to return anything with exponent equal to or lower than the given exponent.
This was still working because we were still (incorrectly) decrementing the exponent passed to `preround` in the first place, passing one less than the target exponent instead of the target exponent itself.
This PR fixes both issues.
Not a user-facing bug, since the functions exposed in the API continued to work as expected.
=> Fix preround for Fraction and float types

.github/workflows/qc.yaml, pyproject.toml
This PR bumps the minimum Python required version to 3.8, and updates the CI workflow to add tests on Python 3.12 and Python 3.13.
=> Update minimum Python version to 3.8; test on 3.12 and 3.13

.flake8, .github/workflows/qc-requirements.txt, .github/workflows/qc.yaml, pyproject.toml
This PR replaces use of `black`, `flake8` and `isort` with `ruff`.
=> Switch to ruff for formatting and linting

src/rounders/decimal_overloads.py, src/rounders/float_overloads.py, src/rounders/fraction_overloads.py, src/rounders/generics.py, src/rounders/int_overloads.py, src/rounders/intermediate.py, src/rounders/test/test_round_for_format.py
[Pushing an ancient branch to GitHub, for self-review purposes]
This PR adds support for formatting in the case where both `format.maximum_figures` and `format.minimum_exponent` are `None`. In that case, formatting should either give a representation of the exact value, or it should fail.
- support the formatting case where both `format.maximum_figures` and `format.minimum_exponent` are `None`: in that case, formatting should either give a representation of the exact value, or fail
- support an exponent of `None` in `IntermediateForm.from_signed_fraction`
- make exponent optional in `preround`: if `exponent` is `None`, then either an exact conversion to the intermediate form is performed, or if that isn't possible, `ValueError` is raised.
=> Support exact formatting

pyproject.toml
This PR introduces use of `setuptools_scm` for versioning. It also tidies up the `pyproject.toml` a bit, removing outdated configs for `isort` and `black`, and reformatting some entries.
=> Add setuptools_scm for versioning

pyproject.toml
Use the release-branch-semver versioning scheme, to get sensible versions from commits on the main branch.
=> Use release-branch-semver versioning scheme

.github/workflows/qc.yaml
Just to make sure that setuptools-scm is working as expected in the workflow build. The repository is fairly tiny, so there's not much of a cost involved in making a full clone each time.
=> Don't use a shallow clone, so that we get the correct version

changelog.d/20240608_172515_dickinsm.md, doc/todo.txt, src/rounders/modes.py
This PR updates the repr of the various rounding modes.
Before:
```python
Python 3.12.3 (main, Apr 12 2024, 17:19:53) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rounders import *
>>> TO_EVEN
<rounders.modes._StandardRoundingMode object at 0x10ea66c00>
>>> TIES_TO_AWAY
<rounders.modes._StandardRoundingMode object at 0x10ea66a80>
>>> TO_ZERO_05_AWAY
<rounders.modes._RoundForReroundRoundingMode object at 0x10ea66930>
```
After:
```python
Python 3.12.3 (main, Apr 12 2024, 17:19:53) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rounders import *
>>> TO_EVEN
<RoundingMode: to even>
>>> TIES_TO_AWAY
<RoundingMode: ties to away>
>>> …
```
=> Give RoundingMode a more useful repr

src/rounders/test/test_round.py
This PR adds some additional tests for the 12 standard rounding functions / rounding modes. The goal is to reduce the risk of copy-and-paste errors between the various rounding modes, and provide at-a-glance representations of the rounding modes that are easier to validate than the current tests.
=> Add tests for round function 'signatures'

src/rounders/format.py, src/rounders/intermediate.py
Typing nitpick: use `from __future__ import annotations` where relevant so that we can drop quoting of return types.
=> Remove quotes around types

.github/workflows/publish.yml, CHANGELOG.md
This PR adds a workflow for automated publication of GitHub releases to PyPI, following instructions at https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi#adding-the-identity-provider-to-pypi.
(See also https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)
=> Add workflow for automatic publication of releases to PyPI

pyproject.toml
This PR adds a basic configuration for coverage, so that `coverage run -m pytest`:
- always runs branch coverage
- measures all files in the package, even if they're not touched by the test suite
=> Add configuration for coverage tool

changelog.d/20240616_121201_dickinsm_intermediate_form_from_str.md, src/rounders/intermediate.py, src/rounders/test/test_intermediate_form.py
This PR adds an `IntermediateForm.from_str` method, with the goal of making it easier to create `IntermediateForm` objects for use in unit tests.
=> Add IntermediateForm.from_str

changelog.d/20240616_152511_dickinsm_weaken_decade_requirement.md, src/rounders/generics.py, src/rounders/intermediate.py, src/rounders/round_to.py
This PR weakens the requirements on `decade` overloads: overloads may return an underestimate for the decade in situations where it's computationally expensive to determine the exact decade.
=> Allow decade to be an underestimate

changelog.d/20240629_165752_dickinsm.md, src/rounders/format.py, src/rounders/intermediate_form.py, src/rounders/round_to.py, src/rounders/test/test_intermediate_form.py
Minor update to replace `IntermediateForm.nudge` with something more general (and better named).
=> Replace IntermediateForm.nudge with more general IntermediateForm.trim

src/rounders/intermediate_form.py, src/rounders/test/test_intermediate_form.py
Add a simple string representation for `IntermediateForm`, with tests.
=> Add IntermediateForm.__str__

.github/workflows/qc-requirements.txt, .github/workflows/test.yml
Follow-on to PR #60: this simplifies the "qc" workflow and renames it to test, since that's now all that it's doing.
=> Simplify test workflow
